import {useEffect,useMemo,useState} from 'react'
import './liveShadow.css'
import './midpointStrategyShadow.css'

type AuditEvent={event_id:string;session_date:string;strategy:string;version:string;family:string|null;event_timestamp:string;event_type:string;direction:string|null;state_before:string|null;state_after:string|null;result:string|null;reason:string|null;underlying_price:number|null;directional_points:number|null;reference_type:string|null;reference_high:number|null;reference_low:number|null;midpoint:number|null;original_boundary:number|null;futures_price:number|null;futures_vwap:number|null;directional_vwap_value:number|null;evidence:Record<string,any>;observation_only:boolean;execution_enabled:boolean;paper_order_enabled:boolean;quantity:null}
type WorkspaceStatus={workspace:string;display_name:string;version:string;mode:string;families:Record<string,{enabled:boolean}>;management:Record<string,any>;safety:{observation_only:boolean;execution_enabled:boolean;paper_order_enabled:boolean;quantity:null}}
type Status={model:string;mode?:string;workspace:WorkspaceStatus;audit_record_count:number;session_dates?:string[];event_counts:Record<string,number>;family_b_state:string;latest_event:AuditEvent|null;latest_entry:AuditEvent|null;latest_plus20:AuditEvent|null;latest_classifier:AuditEvent|null;latest_degraded:AuditEvent|null;latest_recovery:AuditEvent|null;latest_rescue:AuditEvent|null;latest_reentry:AuditEvent|null;latest_terminal?:AuditEvent|null;safety:WorkspaceStatus['safety']}
type TimelineRow={event_id:string;session_date?:string|null;timestamp:string;event_type:string;family?:string|null;display_owner?:string|null;direction:string|null;state_before:string|null;state_after:string|null;result:string|null;reason:string|null;underlying_price:number|null;directional_points:number|null;reference_type?:string|null}
type ReplayMinute={session_date:string;timestamp:string;underlying_open:number|null;underlying_high:number|null;underlying_low:number|null;underlying_close:number|null;futures_close:number|null;futures_vwap:number|null;data_status:string;events:TimelineRow[]}
type Session={session_date:string;block?:string|null;event_count?:number|null;minute_count?:number|null;first_minute?:string|null;last_minute?:string|null;source:string;status:string}
type HistResponse={session_date:string;status:Status;count:number;timeline:TimelineRow[];minute_count:number;minutes:ReplayMinute[]}

const base='/api/live-shadow/midpoint-strategy'
const get=async<T,>(path:string):Promise<T>=>{const r=await fetch(base+path);if(!r.ok){const e=await r.json().catch(()=>null);throw new Error(e?.detail||'Midpoint Strategy request failed')}return r.json()}
const words=(v:any)=>v==null?'—':String(v).replaceAll('_',' ')
const num=(v:any,d=2)=>v==null?'—':Number(v).toLocaleString('en-IN',{maximumFractionDigits:d})
const dt=(v:string|null|undefined)=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:false}):'—'
const tm=(v:string|null|undefined)=>v?new Date(v).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false}):'—'
const yn=(v:any)=>v?'YES':'NO'
const eventClass=(v:string)=>{const x=String(v||'').toUpperCase();if(x.includes('ENTRY'))return'mp-entry';if(x==='PLUS20_PROOF'||x.includes('RUNNER_STRENGTHENING'))return'mp-positive';if(x.includes('DEGRADED'))return'mp-warning';if(x.includes('CAP20'))return'mp-rescue';if(x.includes('STRUCTURAL_TERMINAL')||x.includes('INVALIDATED')||x.includes('EXPIRED'))return'mp-terminal';if(x.includes('BOUNDARY'))return'mp-boundary';if(x.includes('MIDPOINT'))return'mp-midpoint';return'mp-neutral'}
const semanticOwner=(event:Partial<AuditEvent&TimelineRow>|null|undefined)=>{if(!event)return'—';if(event.display_owner)return event.display_owner;const et=String(event.event_type??'').toUpperCase();const reason=String(event.reason??'').toUpperCase();const family=String(event.family??'').toUpperCase();if(et==='BOUNDARY_OWNER_OTHER'&&reason==='FRESH_CANDIDATE_A_AT_BOUNDARY')return'FRESH A';if(family==='OTHER_FRESH_A')return'FRESH A';return words(event.family)}

function EventCard({label,event}:{label:string;event:AuditEvent|null|undefined}){return <article className={`mp-card ${eventClass(event?.event_type??'')}`}><span>{label}</span><b>{event?words(event.result||event.event_type):'—'}</b><small>{event?`${tm(event.event_timestamp)} · ${words(event.reason)}`:'No event yet'}</small></article>}

function AuditDetail({event}:{event:AuditEvent}){return <div className="hilega-audit-body mp-audit-detail"><div className="shadow-detail-grid"><span>Event <b>{words(event.event_type)}</b></span><span>Timestamp <b>{dt(event.event_timestamp)}</b></span><span>Owner <b>{semanticOwner(event)}</b></span><span>Direction <b>{words(event.direction)}</b></span><span>Result <b>{words(event.result)}</b></span><span>Reason <b>{words(event.reason)}</b></span><span>Reference <b>{words(event.reference_type)}</b></span><span>Reference high <b>{num(event.reference_high)}</b></span><span>Midpoint <b>{num(event.midpoint)}</b></span><span>Reference low <b>{num(event.reference_low)}</b></span><span>Original boundary <b>{num(event.original_boundary)}</b></span><span>NIFTY <b>{num(event.underlying_price)}</b></span><span>Directional points <b>{num(event.directional_points)}</b></span><span>Futures <b>{num(event.futures_price)}</b></span><span>Futures VWAP <b>{num(event.futures_vwap)}</b></span><span>Directional VWAP <b>{num(event.directional_vwap_value)}</b></span><span>Observation only <b>{yn(event.observation_only)}</b></span><span>Execution <b>{event.execution_enabled?'ENABLED':'DISABLED'}</b></span></div><div className="hilega-audit-section"><b>Decision evidence</b><pre>{JSON.stringify(event.evidence??{},null,2)}</pre></div><div className="hilega-audit-section"><b>Raw immutable audit event</b><pre>{JSON.stringify(event,null,2)}</pre></div></div>}

function AuditDrawer({event,onClose}:{event:AuditEvent;onClose:()=>void}){return <div className="mp-drawer-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="mp-audit-drawer" role="dialog" aria-modal="true" aria-label="Midpoint audit detail"><div className="mp-drawer-head"><div><span>IMMUTABLE AUDIT</span><h2>{words(event.event_type)}</h2><small>{dt(event.event_timestamp)}</small></div><button className="secondary" onClick={onClose}>Close</button></div><AuditDetail event={event}/></aside></div>}

function LiveAuditTable({timeline,onInspect}:{timeline:TimelineRow[];onInspect:(id:string)=>void}){return <section className="panel shadow-panel"><div className="panel-heading"><div><h2>Midpoint candle-by-candle decision audit</h2><p>Latest two available live sessions. Click Inspect for full evidence.</p></div><span className="pill teal">LIVE</span></div><div className="shadow-table-scroll mp-table-scroll"><table className="shadow-table mp-table"><thead><tr><th>Time</th><th>Session</th><th>Event</th><th>Owner</th><th>Direction</th><th>State</th><th>Result</th><th>Reason</th><th>NIFTY</th><th>Points</th><th>Audit</th></tr></thead><tbody>{[...timeline].reverse().map(x=><tr key={x.event_id} className={eventClass(x.event_type)}><td>{tm(x.timestamp)}</td><td>{x.session_date??'—'}</td><td><b>{words(x.event_type)}</b></td><td>{semanticOwner(x)}</td><td>{words(x.direction)}</td><td>{words(x.state_after||x.state_before)}</td><td>{words(x.result)}</td><td className="mp-reason">{words(x.reason)}</td><td>{num(x.underlying_price)}</td><td>{num(x.directional_points)}</td><td><button className="secondary" onClick={()=>onInspect(x.event_id)}>Inspect</button></td></tr>)}{!timeline.length&&<tr><td colSpan={11} className="empty">No Midpoint audit evidence for this view.</td></tr>}</tbody></table></div></section>}

function ReplayMinuteTable({minutes,onInspect}:{minutes:ReplayMinute[];onInspect:(id:string)=>void}){return <section className="panel shadow-panel"><div className="panel-heading"><div><h2>Full-day minute replay</h2><p>One selected trading date. Strategy events are overlaid on the exact available minute evidence.</p></div><span className="pill teal">REPLAY</span></div><div className="shadow-table-scroll mp-minute-scroll"><table className="shadow-table mp-minute-table"><thead><tr><th>Time</th><th>NIFTY O</th><th>H</th><th>L</th><th>C</th><th>Fut close</th><th>Fut VWAP</th><th>Data</th><th>Strategy event / audit</th></tr></thead><tbody>{minutes.map(m=>{const first=m.events?.[0];return <tr key={m.timestamp} className={first?eventClass(first.event_type):'mp-minute-plain'}><td><b>{tm(m.timestamp)}</b></td><td>{num(m.underlying_open)}</td><td>{num(m.underlying_high)}</td><td>{num(m.underlying_low)}</td><td>{num(m.underlying_close)}</td><td>{num(m.futures_close)}</td><td>{num(m.futures_vwap)}</td><td><span className={`mp-data-status ${m.data_status!=='BOTH'?'warn':''}`}>{words(m.data_status)}</span></td><td>{m.events?.length?<div className="mp-minute-events">{m.events.map(e=><div className="mp-minute-event" key={e.event_id}><div><b>{words(e.event_type)}</b><small>{semanticOwner(e)} · {words(e.direction)} · {words(e.result)}</small><small>{words(e.reason)}</small></div><button className="secondary" onClick={()=>onInspect(e.event_id)}>Inspect</button></div>)}</div>:<span className="mp-no-event">—</span>}</td></tr>})}{!minutes.length&&<tr><td colSpan={9} className="empty">No full-day minute evidence materialized for this date.</td></tr>}</tbody></table></div></section>}

function SessionView({mode,status,timeline,minutes,selected,onInspect,onClose}:{mode:'LIVE'|'HISTORICAL_REPLAY';status:Status|null;timeline:TimelineRow[];minutes:ReplayMinute[];selected:AuditEvent|null;onInspect:(id:string)=>void;onClose:()=>void}){
 const current=status?.latest_event
 return <><div className="shadow-safety"><b>MIDPOINT STRATEGY · {mode==='LIVE'?'OBSERVATION ONLY':'HISTORICAL REPLAY'}</b><span>Execution disabled</span><span>Paper orders disabled</span><span>Quantity none</span><span>{mode==='LIVE'?'Current + previous available trading session':'One selected trading date'}</span></div>
 <div className="shadow-metrics mp-summary"><article><span>Owner</span><b>{semanticOwner(current??status?.latest_entry)}</b><small>FRESH A = fresh Candidate A owns boundary; not B/E</small></article><article><span>Direction</span><b>{words(current?.direction)}</b><small>{words(current?.reference_type)} reference</small></article><article><span>Family state</span><b>{words(status?.family_b_state)}</b><small>{status?.audit_record_count??0} strategy events</small></article><article><span>Latest event</span><b>{words(current?.event_type)}</b><small>{tm(current?.event_timestamp)}</small></article><article><span>Boundary / midpoint</span><b>{num(current?.original_boundary)} / {num(current?.midpoint)}</b><small>High {num(current?.reference_high)} · Low {num(current?.reference_low)}</small></article><article><span>Safety</span><b>{status?.safety.observation_only?'SAFE':'CHECK'}</b><small>Execution {status?.safety.execution_enabled?'ON':'OFF'} · Paper {status?.safety.paper_order_enabled?'ON':'OFF'}</small></article></div>
 <div className="mp-lifecycle-grid"><EventCard label="Entry" event={status?.latest_entry}/><EventCard label="+20 proof" event={status?.latest_plus20}/><EventCard label="Runner classification" event={status?.latest_classifier}/><EventCard label="Degraded" event={status?.latest_degraded}/><EventCard label="CAP20 rescue" event={status?.latest_rescue}/><EventCard label="Structural terminal" event={status?.latest_terminal}/></div>
 {mode==='HISTORICAL_REPLAY'?<ReplayMinuteTable minutes={minutes} onInspect={onInspect}/>:<LiveAuditTable timeline={timeline} onInspect={onInspect}/>} 
 {selected&&<AuditDrawer event={selected} onClose={onClose}/>}</>
}

export default function MidpointStrategyShadow(){
 const [mode,setMode]=useState<'LIVE'|'HISTORICAL_REPLAY'>('LIVE')
 const [status,setStatus]=useState<Status|null>(null)
 const [timeline,setTimeline]=useState<TimelineRow[]>([])
 const [minutes,setMinutes]=useState<ReplayMinute[]>([])
 const [sessions,setSessions]=useState<Session[]>([])
 const [selectedDate,setSelectedDate]=useState('')
 const [selected,setSelected]=useState<AuditEvent|null>(null)
 const [error,setError]=useState('')
 const [loading,setLoading]=useState(true)

 const refreshLive=async()=>{try{const [s,t]=await Promise.all([get<Status>('/status'),get<{timeline:TimelineRow[]}>('/timeline?limit=200')]);setStatus(s);setTimeline(t.timeline);setMinutes([]);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const fetchReplay=async(date:string)=>{if(!date)return;setLoading(true);setSelected(null);try{const r=await get<HistResponse>('/historical/session?session_date='+encodeURIComponent(date));setSelectedDate(date);setStatus(r.status);setTimeline(r.timeline);setMinutes(r.minutes??[]);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}

 useEffect(()=>{if(mode!=='LIVE')return;let active=true;const poll=()=>{if(active)void refreshLive()};poll();const id=window.setInterval(poll,5000);return()=>{active=false;window.clearInterval(id)}},[mode])
 useEffect(()=>{if(mode!=='HISTORICAL_REPLAY')return;let active=true;setLoading(true);void (async()=>{try{const r=await get<{sessions:Session[]}>('/historical/sessions');if(!active)return;const available=r.sessions??[];setSessions(available);const date=available.some(x=>x.session_date===selectedDate)?selectedDate:(available[0]?.session_date??'');setSelectedDate(date);if(date){const replay=await get<HistResponse>('/historical/session?session_date='+encodeURIComponent(date));if(!active)return;setStatus(replay.status);setTimeline(replay.timeline);setMinutes(replay.minutes??[]);setError('')}else{setStatus(null);setTimeline([]);setMinutes([])}}catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[mode])

 const inspect=async(eventId:string)=>{try{const path=mode==='LIVE'?'/audit-detail?event_id='+encodeURIComponent(eventId):'/historical/audit-detail?session_date='+encodeURIComponent(selectedDate)+'&event_id='+encodeURIComponent(eventId);const r=await get<{event:AuditEvent}>(path);setSelected(r.event);setError('')}catch(e){setError((e as Error).message)}}
 const latestSessions=useMemo(()=>status?.session_dates??[],[status])
 const orderedDates=useMemo(()=>sessions.map(x=>x.session_date).sort(),[sessions])
 const selectedIndex=orderedDates.indexOf(selectedDate)
 const previousDate=selectedIndex>0?orderedDates[selectedIndex-1]:''
 const nextDate=selectedIndex>=0&&selectedIndex<orderedDates.length-1?orderedDates[selectedIndex+1]:''
 const selectedSession=sessions.find(x=>x.session_date===selectedDate)

 return <div className="shadow-page hilega-page midpoint-page">{error&&<div role="alert" className="banner error">{error}</div>}<div className="mp-modebar"><div><button className={mode==='LIVE'?'primary':'secondary'} onClick={()=>{setMode('LIVE');setSelected(null);setLoading(true)}}>Live shadow</button><button className={mode==='HISTORICAL_REPLAY'?'primary':'secondary'} onClick={()=>{setMode('HISTORICAL_REPLAY');setSelected(null);setLoading(true)}}>Historical replay</button></div>{mode==='LIVE'?<small>Visible sessions: {latestSessions.length?latestSessions.join(' + '):'waiting for audit'}</small>:<div className="mp-replay-controls"><button className="secondary" disabled={!previousDate||loading} onClick={()=>void fetchReplay(previousDate)}>← Previous date</button><select value={selectedDate} disabled={loading&&!sessions.length} onChange={e=>void fetchReplay(e.target.value)}>{!sessions.length&&<option value="">No materialized sessions</option>}{sessions.map(x=><option key={x.session_date} value={x.session_date}>{x.session_date} · {x.minute_count??0} min · {x.event_count??0} events</option>)}</select><button className="secondary" disabled={!nextDate||loading} onClick={()=>void fetchReplay(nextDate)}>Next date →</button><button className="primary" disabled={!selectedDate||loading} onClick={()=>void fetchReplay(selectedDate)}>{loading?'Loading…':'Reload date'}</button></div>}</div>{mode==='HISTORICAL_REPLAY'&&selectedDate&&<div className="mp-replay-banner"><b>HISTORICAL REPLAY</b><span>{selectedDate}</span><span>{minutes.length} minute rows</span><span>{timeline.length} strategy events</span><small>{selectedSession?.block??'tested source'} · V57 parity-proven strategy replay · manual validation · no broker / no execution</small></div>}{loading&&!status?<section className="panel"><div className="empty">Loading Midpoint Strategy…</div></section>:<SessionView mode={mode} status={status} timeline={timeline} minutes={minutes} selected={selected} onInspect={id=>void inspect(id)} onClose={()=>setSelected(null)}/>}</div>
}
