import {useEffect,useMemo,useState} from 'react'
import './liveShadow.css'
import './midpointStrategyShadow.css'

type AuditEvent={event_id:string;session_date:string;strategy:string;version:string;family:string;event_timestamp:string;event_type:string;direction:string|null;state_before:string|null;state_after:string|null;result:string|null;reason:string|null;underlying_price:number|null;directional_points:number|null;reference_type:string|null;reference_high:number|null;reference_low:number|null;midpoint:number|null;original_boundary:number|null;futures_price:number|null;futures_vwap:number|null;directional_vwap_value:number|null;evidence:Record<string,any>;observation_only:boolean;execution_enabled:boolean;paper_order_enabled:boolean;quantity:null}
type WorkspaceStatus={workspace:string;display_name:string;version:string;mode:string;families:Record<string,{enabled:boolean}>;management:Record<string,any>;safety:{observation_only:boolean;execution_enabled:boolean;paper_order_enabled:boolean;quantity:null}}
type Status={model:string;mode?:string;workspace:WorkspaceStatus;audit_record_count:number;session_dates?:string[];event_counts:Record<string,number>;family_b_state:string;latest_event:AuditEvent|null;latest_entry:AuditEvent|null;latest_plus20:AuditEvent|null;latest_classifier:AuditEvent|null;latest_degraded:AuditEvent|null;latest_recovery:AuditEvent|null;latest_rescue:AuditEvent|null;latest_reentry:AuditEvent|null;latest_terminal?:AuditEvent|null;safety:WorkspaceStatus['safety']}
type TimelineRow={event_id:string;session_date?:string|null;timestamp:string;event_type:string;family?:string|null;direction:string|null;state_before:string|null;state_after:string|null;result:string|null;reason:string|null;underlying_price:number|null;directional_points:number|null;reference_type?:string|null}
type Session={session_date:string;block?:string|null;event_count?:number|null;source:string;status:string}
type HistResponse={session_date:string;status:Status;count:number;timeline:TimelineRow[]}

const base='/api/live-shadow/midpoint-strategy'
const get=async<T,>(path:string):Promise<T>=>{const r=await fetch(base+path);if(!r.ok){const e=await r.json().catch(()=>null);throw new Error(e?.detail||'Midpoint Strategy request failed')}return r.json()}
const words=(v:any)=>v==null?'—':String(v).replaceAll('_',' ')
const owner=(v:any)=>String(v??'').toUpperCase()==='OTHER_FRESH_A'?'FRESH A':words(v)
const num=(v:any,d=2)=>v==null?'—':Number(v).toLocaleString('en-IN',{maximumFractionDigits:d})
const dt=(v:string|null|undefined)=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:false}):'—'
const tm=(v:string|null|undefined)=>v?new Date(v).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false}):'—'
const yn=(v:any)=>v?'YES':'NO'
const eventClass=(v:string)=>{const x=String(v||'').toUpperCase();if(x.includes('ENTRY'))return'mp-entry';if(x==='PLUS20_PROOF'||x.includes('RUNNER_STRENGTHENING'))return'mp-positive';if(x.includes('DEGRADED'))return'mp-warning';if(x.includes('CAP20'))return'mp-rescue';if(x.includes('STRUCTURAL_TERMINAL')||x.includes('INVALIDATED')||x.includes('EXPIRED'))return'mp-terminal';if(x.includes('BOUNDARY'))return'mp-boundary';if(x.includes('MIDPOINT'))return'mp-midpoint';return'mp-neutral'}

function EventCard({label,event}:{label:string;event:AuditEvent|null|undefined}){return <article className={`mp-card ${eventClass(event?.event_type??'')}`}><span>{label}</span><b>{event?words(event.result||event.event_type):'—'}</b><small>{event?`${tm(event.event_timestamp)} · ${words(event.reason)}`:'No event yet'}</small></article>}
function AuditDetail({event}:{event:AuditEvent}){return <div className="hilega-audit-body mp-audit-detail"><div className="shadow-detail-grid"><span>Event <b>{words(event.event_type)}</b></span><span>Timestamp <b>{dt(event.event_timestamp)}</b></span><span>Owner <b>{owner(event.family)}</b></span><span>Direction <b>{words(event.direction)}</b></span><span>Result <b>{words(event.result)}</b></span><span>Reason <b>{words(event.reason)}</b></span><span>Reference <b>{words(event.reference_type)}</b></span><span>Reference high <b>{num(event.reference_high)}</b></span><span>Midpoint <b>{num(event.midpoint)}</b></span><span>Reference low <b>{num(event.reference_low)}</b></span><span>Original boundary <b>{num(event.original_boundary)}</b></span><span>NIFTY <b>{num(event.underlying_price)}</b></span><span>Directional points <b>{num(event.directional_points)}</b></span><span>Futures <b>{num(event.futures_price)}</b></span><span>Futures VWAP <b>{num(event.futures_vwap)}</b></span><span>Directional VWAP <b>{num(event.directional_vwap_value)}</b></span><span>Observation only <b>{yn(event.observation_only)}</b></span><span>Execution <b>{event.execution_enabled?'ENABLED':'DISABLED'}</b></span></div><div className="hilega-audit-section"><b>Decision evidence</b><pre>{JSON.stringify(event.evidence??{},null,2)}</pre></div><div className="hilega-audit-section"><b>Raw immutable audit event</b><pre>{JSON.stringify(event,null,2)}</pre></div></div>}

function SessionView({mode,status,timeline,selected,onInspect,onClose}:{mode:'LIVE'|'HISTORICAL_REPLAY';status:Status|null;timeline:TimelineRow[];selected:AuditEvent|null;onInspect:(id:string)=>void;onClose:()=>void}){
 const current=status?.latest_event
 return <><div className="shadow-safety"><b>MIDPOINT STRATEGY · {mode==='LIVE'?'OBSERVATION ONLY':'HISTORICAL REPLAY'}</b><span>Execution disabled</span><span>Paper orders disabled</span><span>Quantity none</span><span>{mode==='LIVE'?'Today + previous trading session':'Manual validation mode'}</span></div>
 <div className="shadow-metrics mp-summary"><article><span>Owner</span><b>{owner(current?.family??status?.latest_entry?.family)}</b><small>FRESH A = fresh Candidate A owns boundary; not B/E</small></article><article><span>Direction</span><b>{words(current?.direction)}</b><small>{words(current?.reference_type)} reference</small></article><article><span>Family state</span><b>{words(status?.family_b_state)}</b><small>{status?.audit_record_count??0} visible audit records</small></article><article><span>Latest event</span><b>{words(current?.event_type)}</b><small>{tm(current?.event_timestamp)}</small></article><article><span>Boundary / midpoint</span><b>{num(current?.original_boundary)} / {num(current?.midpoint)}</b><small>High {num(current?.reference_high)} · Low {num(current?.reference_low)}</small></article><article><span>Safety</span><b>{status?.safety.observation_only?'SAFE':'CHECK'}</b><small>Execution {status?.safety.execution_enabled?'ON':'OFF'} · Paper {status?.safety.paper_order_enabled?'ON':'OFF'}</small></article></div>
 <div className="mp-lifecycle-grid"><EventCard label="Entry" event={status?.latest_entry}/><EventCard label="+20 proof" event={status?.latest_plus20}/><EventCard label="Runner classification" event={status?.latest_classifier}/><EventCard label="Degraded" event={status?.latest_degraded}/><EventCard label="CAP20 rescue" event={status?.latest_rescue}/><EventCard label="Structural terminal" event={status?.latest_terminal}/></div>
 <section className="panel shadow-panel"><div className="panel-heading"><div><h2>Midpoint candle-by-candle decision audit</h2><p>Same validation presentation for live and replay. Click Inspect for full evidence.</p></div><span className="pill teal">{mode==='LIVE'?'LIVE':'REPLAY'}</span></div><div className="shadow-table-scroll mp-table-scroll"><table className="shadow-table mp-table"><thead><tr><th>Time</th><th>Session</th><th>Event</th><th>Owner</th><th>Direction</th><th>State</th><th>Result</th><th>Reason</th><th>NIFTY</th><th>Points</th><th>Audit</th></tr></thead><tbody>{[...timeline].reverse().map(x=><tr key={x.event_id} className={eventClass(x.event_type)}><td>{tm(x.timestamp)}</td><td>{x.session_date??'—'}</td><td><b>{words(x.event_type)}</b></td><td>{owner(x.family)}</td><td>{words(x.direction)}</td><td>{words(x.state_after||x.state_before)}</td><td>{words(x.result)}</td><td className="mp-reason">{words(x.reason)}</td><td>{num(x.underlying_price)}</td><td>{num(x.directional_points)}</td><td><button className="secondary" onClick={()=>onInspect(x.event_id)}>Inspect</button></td></tr>)}{!timeline.length&&<tr><td colSpan={11} className="empty">No Midpoint audit evidence for this view.</td></tr>}</tbody></table></div></section>
 {selected&&<section className="panel shadow-panel"><div className="panel-heading"><div><h2>Detailed audit</h2><p>Exact immutable event and decision evidence.</p></div><button className="secondary" onClick={onClose}>Close</button></div><AuditDetail event={selected}/></section>}</>
}

export default function MidpointStrategyShadow(){
 const [mode,setMode]=useState<'LIVE'|'HISTORICAL_REPLAY'>('LIVE');const [status,setStatus]=useState<Status|null>(null);const [timeline,setTimeline]=useState<TimelineRow[]>([]);const [sessions,setSessions]=useState<Session[]>([]);const [selectedDate,setSelectedDate]=useState('');const [selected,setSelected]=useState<AuditEvent|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true)
 const refreshLive=async()=>{const [s,t]=await Promise.all([get<Status>('/status'),get<{timeline:TimelineRow[]}>('/timeline?limit=200')]);setStatus(s);setTimeline(t.timeline);setError('');setLoading(false)}
 const refreshSessions=async()=>{const r=await get<{sessions:Session[]}>('/historical/sessions');setSessions(r.sessions??[]);setSelectedDate(prev=>r.sessions.some(x=>x.session_date===prev)?prev:(r.sessions[0]?.session_date??''))}
 useEffect(()=>{if(mode!=='LIVE')return;let active=true;const poll=()=>void refreshLive().catch(e=>active&&setError((e as Error).message));poll();const id=window.setInterval(poll,5000);return()=>{active=false;window.clearInterval(id)}},[mode])
 useEffect(()=>{if(mode==='HISTORICAL_REPLAY')void refreshSessions().catch(e=>setError((e as Error).message))},[mode])
 const loadReplay=async()=>{if(!selectedDate)return;setLoading(true);setSelected(null);try{const r=await get<HistResponse>('/historical/session?session_date='+encodeURIComponent(selectedDate));setStatus(r.status);setTimeline(r.timeline);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const inspect=async(eventId:string)=>{try{const path=mode==='LIVE'?'/audit-detail?event_id='+encodeURIComponent(eventId):'/historical/audit-detail?session_date='+encodeURIComponent(selectedDate)+'&event_id='+encodeURIComponent(eventId);const r=await get<{event:AuditEvent}>(path);setSelected(r.event)}catch(e){setError((e as Error).message)}}
 const latestSessions=useMemo(()=>status?.session_dates??[],[status])
 return <div className="shadow-page hilega-page midpoint-page">{error&&<div role="alert" className="banner error">{error}</div>}<div className="mp-modebar"><div><button className={mode==='LIVE'?'primary':'secondary'} onClick={()=>{setMode('LIVE');setSelected(null)}}>Live shadow</button><button className={mode==='HISTORICAL_REPLAY'?'primary':'secondary'} onClick={()=>{setMode('HISTORICAL_REPLAY');setStatus(null);setTimeline([]);setSelected(null)}}>Historical replay</button></div>{mode==='LIVE'?<small>Visible sessions: {latestSessions.length?latestSessions.join(' + '):'waiting for audit'}</small>:<div className="mp-replay-controls"><select value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}>{!sessions.length&&<option value="">No materialized sessions</option>}{sessions.map(x=><option key={x.session_date} value={x.session_date}>{x.session_date} · {x.block??'tested'} · {x.event_count??0} events</option>)}</select><button className="primary" disabled={!selectedDate||loading} onClick={()=>void loadReplay()}>{loading?'Loading…':'Load replay'}</button></div>}</div>{mode==='HISTORICAL_REPLAY'&&selectedDate&&<div className="mp-replay-banner"><b>HISTORICAL REPLAY</b><span>{selectedDate}</span><small>V57 parity-proven source · manual validation · no broker / no execution</small></div>}{loading&&!status?<section className="panel"><div className="empty">Loading Midpoint Strategy…</div></section>:<SessionView mode={mode} status={status} timeline={timeline} selected={selected} onInspect={id=>void inspect(id)} onClose={()=>setSelected(null)}/>}</div>
}
