"""Canonical, immutable and runtime-independent Red Bar V2 contracts."""

from .enums import (
    AdmissionOutcome,
    BundleLifecycleStatus,
    ContextStatus,
    Direction,
    EntryType,
    OptionSide,
    RedBarV2Section1Outcome,
    RedBarV2State,
    TrendStrength,
)
from .exceptions import (
    BundleIdentityError,
    DomainValidationError,
    RedBarV2DomainError,
    UnsupportedSchemaVersionError,
)
from .exit_policy import (
    ExitReason,
    OpenPosition,
    TradeOutcome,
    advance,
    open_position,
)
from .identity import (
    build_red_bar_v2_bundle_id,
    build_red_bar_v2_idempotency_key,
    build_red_bar_v2_signal_id,
)
from .models import (
    FuturesVwapEvidence,
    MarketTimestampEvidence,
    MidpointEvidence,
    RedBarV2Decision,
    RedBarV2InputReadiness,
    RedBarV2Reference,
    RedBarV2SignalBundle,
    RsiEvidence,
)
from .risk import (
    DEFAULT_MAXIMUM_RISK_POINTS,
    DEFAULT_MINIMUM_RISK_POINTS,
    DEFAULT_QUANTITY_LOTS,
    DEFAULT_REWARD_MULTIPLE,
    DEFAULT_SESSION_FLAT_TIME,
    DEFAULT_TRAIL_ACTIVATION_R,
    Bar,
    RiskPlan,
    RiskPlanRejected,
    RiskPlanRejection,
    StopTrigger,
    StopTriggerCandle,
    TriggerResolution,
    build_risk_plan,
    find_stop_trigger,
)
from .serialization import (
    SUPPORTED_SCHEMA_VERSIONS,
    red_bar_v2_bundle_from_dict,
    red_bar_v2_bundle_to_dict,
    red_bar_v2_resolution_to_dict,
)

__all__ = [
    "AdmissionOutcome",
    "Bar",
    "BundleIdentityError",
    "BundleLifecycleStatus",
    "ContextStatus",
    "DEFAULT_MAXIMUM_RISK_POINTS",
    "DEFAULT_MINIMUM_RISK_POINTS",
    "DEFAULT_QUANTITY_LOTS",
    "DEFAULT_REWARD_MULTIPLE",
    "DEFAULT_SESSION_FLAT_TIME",
    "DEFAULT_TRAIL_ACTIVATION_R",
    "Direction",
    "DomainValidationError",
    "EntryType",
    "ExitReason",
    "FuturesVwapEvidence",
    "MarketTimestampEvidence",
    "MidpointEvidence",
    "OpenPosition",
    "OptionSide",
    "RedBarV2Decision",
    "RedBarV2DomainError",
    "RedBarV2InputReadiness",
    "RedBarV2Reference",
    "RedBarV2Section1Outcome",
    "RedBarV2SignalBundle",
    "RedBarV2State",
    "RiskPlan",
    "RiskPlanRejected",
    "RiskPlanRejection",
    "RsiEvidence",
    "SUPPORTED_SCHEMA_VERSIONS",
    "StopTrigger",
    "StopTriggerCandle",
    "TradeOutcome",
    "TrendStrength",
    "TriggerResolution",
    "UnsupportedSchemaVersionError",
    "advance",
    "build_red_bar_v2_bundle_id",
    "build_red_bar_v2_idempotency_key",
    "build_red_bar_v2_signal_id",
    "build_risk_plan",
    "find_stop_trigger",
    "open_position",
    "red_bar_v2_bundle_from_dict",
    "red_bar_v2_bundle_to_dict",
    "red_bar_v2_resolution_to_dict",
]
