"""Enumerate the third-party imports used by the red_bar_lab package.

Writes:
  - extracted_requirements.txt   (pip install -r friendly)
  - imported_by.csv             (per-module import count, for auditing)

Usage:
  python scripts/extract_project_deps.py
"""

from __future__ import annotations

import ast
import csv
import os
import sys
from collections import Counter, defaultdict


ROOT = "red_bar_lab"
OUT_REQ = "extracted_requirements.txt"
OUT_CSV = "imported_by.csv"

# Standard-library names (Python 3.10+). `sys.stdlib_module_names` is the
# canonical set; we also fold in a few common pkg-internal top-level names.
STDLIB: set[str] = set(sys.stdlib_module_names) | {"red_bar_lab"}

# pip-name normalization: import name -> pip distribution
PIP_MAP: dict[str, str] = {
    "PIL": "Pillow",
    "cv2": "opencv-python",
    "yaml": "PyYAML",
    "bs4": "beautifulsoup4",
    "sklearn": "scikit-learn",
    "dotenv": "python-dotenv",
    "dateutil": "python-dateutil",
    "attr": "attrs",
    "gi": "",  # GObject, Linux-only, skip
    "streamlit": "streamlit",
    "altair": "altair",
    "plotly": "plotly",
}


def main() -> int:
    imports: Counter[str] = Counter()
    file_imports: dict[str, set[str]] = defaultdict(set)
    parse_errors: list[tuple[str, str]] = []

    for dirpath, dirnames, filenames in os.walk(ROOT):
        # Skip generated/runtime dirs
        parts = dirpath.split(os.sep)
        if any(p in {"__pycache__", ".pytest_cache", "artifacts"} for p in parts):
            continue
        for fn in filenames:
            if os.path.splitext(fn)[1] != ".py":
                continue
            path = os.path.join(dirpath, fn)
            try:
                with open(path, "r", encoding="utf-8") as f:
                    tree = ast.parse(f.read(), filename=path)
            except SyntaxError as e:
                parse_errors.append((path, str(e)))
                continue
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for n in node.names:
                        top = n.name.split(".")[0]
                        imports[top] += 1
                        file_imports[top].add(path)
                elif isinstance(node, ast.ImportFrom):
                    if node.module is None or node.level > 0:
                        continue
                    top = node.module.split(".")[0]
                    imports[top] += 1
                    file_imports[top].add(path)

    # Build pip list
    pip_lines: list[str] = []
    csv_rows: list[tuple[str, str, int, str]] = []
    for name, count in sorted(imports.items(), key=lambda kv: (-kv[1], kv[0])):
        if name in STDLIB:
            continue
        if name.startswith("red_bar_lab"):
            continue
        pip = PIP_MAP.get(name, name)
        if not pip:
            csv_rows.append((name, "(skipped)", count, ""))
            continue
        # Sample one file for auditing
        sample = sorted(file_imports[name])[0] if file_imports[name] else ""
        pip_lines.append(pip)
        csv_rows.append((name, pip, count, sample))

    with open(OUT_REQ, "w", encoding="utf-8") as f:
        f.write("# Auto-extracted from red_bar_lab/**.py imports\n")
        f.write("# Generated by scripts/extract_project_deps.py\n")
        f.write("# Format: pip distribution name (one per line)\n\n")
        for line in pip_lines:
            f.write(line + "\n")

    with open(OUT_CSV, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["import_name", "pip_name", "file_count", "sample_file"])
        for row in csv_rows:
            w.writerow(row)

    print(f"wrote {OUT_REQ} with {len(pip_lines)} packages")
    print(f"wrote {OUT_CSV} with {len(csv_rows)} import names")
    if parse_errors:
        print(f"WARN: {len(parse_errors)} parse errors:")
        for p, e in parse_errors[:5]:
            print(f"  {p}: {e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
